Task_One.Web/Models/Chart.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Task_One.Web.Models
{
    public class Chart
    {
        public string ProductName { get; set; }
        public string StoreName { get; set; }
        public List<ChartData> Points { get; set; }
    }
}

Task_One.Web/Models/ChartData.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Task_One.Web.Models
{
    public class ChartData
    {
        public DateTime SoldDate { get; set; }
        public double Price { get; set; }
    }
}

Task_One.Web/Models/GroupByChoice.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Task_One.Web.Models
{
    public class GroupByChoice
    {
        public int Value { get; set; }
        public string Text { get; set; }

        public GroupByChoice(int value,string text)
        {
            Text = text;
            Value = value;
        }

        public static List<GroupByChoice> GetChoices()
        {
            List<GroupByChoice> choices = new List<GroupByChoice>();
            choices.Add(new GroupByChoice(1,"Price"));
            choices.Add(new GroupByChoice(2,"Store"));
            choices.Add(new GroupByChoice(3,"Sold Date"));

            return choices;
        }
    }
}

Task_One.Web/Models/ProductSell.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Task_One.Web.Models
{
    public class ProductSell
    {
        public int ProductId { get; set; }
        public int StoreId { get; set; }
        public string Store { get; set; }
        public string Product { get; set; }
        public DateTime SoldDate { get; set; }
        public double Price { get; set; }
    }
}

Task_One.Web/Models/Store.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Task_One.Web.Models
{
    public class Store
    {
        public int StoreId { get; set; }
        public string StoreName { get; set; }
    }
}

Task_One.Web/Controllers/ProductSellsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Rendering;
using Task_One.Web.Models;
using Task_One.Web.Repository.Interfaces;

namespace Task_One.Web.Controllers
{
    public class ProductSellsController : Controller
    {
        private readonly IProductRepository _productRepository;

        public ProductSellsController(IProductRepository productRepository)
        {
            _productRepository = productRepository;
        }

        public IActionResult Index(int storeId,DateTime soldDate,double price)
        {
            ViewBag.Stores = new SelectList(_productRepository.GetStores(), "StoreId", "StoreName");
            ViewBag.SoldDates = new SelectList(_productRepository.GetSoldDates(),"Date","Date");
            ViewBag.Prices = new SelectList(_productRepository.GetPrices());

            var productSells = _productRepository.GetProductSells(storeId, price,
                soldDate);
            return View(productSells);
        }

        [Route("[controller]/[action]/{productId}/{storeId}")]
        public IActionResult GetChart(int productId, int storeId)
        {
            var chart = new Chart();
            chart.ProductName = _productRepository.GetProductName(productId);
            chart.StoreName = _productRepository.GetStoreName(storeId);
            chart.Points = _productRepository.GetPoints(productId, storeId);
            return View(chart);
        }


    }
}

Task_One.Web/Views/ProductSells/GetChart.cshtml
@using System.Globalization
@using Newtonsoft.Json
@model Chart
@{
    ViewData["Title"] = "GetChart";
}

<h3>Price history of product @Model.ProductName in this store @Model.StoreName</h3>
<p>
    <a class="btn btn-primary" href="/productsells">Back</a>
</p>

<hr />

<div id="chartContainer">

</div>

@section Scripts{

    <script src="~/js/canvasjs.min.js"></script>
    <script src="~/js/jquery.canvasjs.min.js"></script>
    <script>
        $(document).ready(function () {
            var dataString = '@Html.Raw(JsonConvert.SerializeObject(Model.Points.Select(p=>new { x=0,year=p.SoldDate.Year,month=p.SoldDate.Month,day=p.SoldDate.Day,y=p.Price})))';
            var dataJson = JSON.parse(dataString);
            for (var i = 0; i < dataJson.length; i++) {
                dataJson[i].x = new Date(dataJson[i].year, dataJson[i].month, dataJson[i].day);
            }
            var chart = new CanvasJS.Chart("chartContainer", {
                animationEnabled: false,
                title: {
                    text: "Price History"
                },
                axisX: {
                    valueFormatString: "DD MMM"
                },
                axisY: {
                    title: "Price",
                    scaleBreaks: {
                        autoCalculate: true
                    }
                },
                data: [{
                    type: "line",
                    xValueFormatString: "DD MMM",
                    color: "#F08080",
                    dataPoints: dataJson
                }]
            });
            chart.render();
        });
    </script>
}

Task_One.Web/Views/ProductSells/Index.cshtml
@model List<ProductSell>
@{
    ViewData["Title"] = "Index";
}

<h1>Sells report</h1>
<hr />
<form method="get">
    <div class="form-group">
        <label for="email">Sold Date : </label>
        <select class="form-control" name="soldDate" asp-items="@ViewBag.SoldDates">
            <option value="0">Please Select One Date : </option>
        </select>
        @*<button type="submit" class="btn btn-primary">Submit</button>*@
    </div>
@*</form>
<form>*@
    <div class="form-group">
        <label for="email">Price : </label>
        <select class="form-control" name="price" asp-items="@ViewBag.Prices">
            <option value="0">Please Select One Price : </option>
        </select>
        @*<button type="submit" class="btn btn-primary">Submit</button>*@
    </div>
@*</form>
<form>*@
    <div class="form-group">
        <label for="email">Store : </label>
        <select class="form-control" name="storeId" asp-items="@ViewBag.Stores">
            <option value="0">Please Select One Store : </option>
        </select>
        @*<button type="submit" class="btn btn-primary">Submit</button>*@
    </div>
@*</form>*@
<button type="submit" class="btn btn-primary">Submit</button>
<a class="btn btn-primary" asp-controller="ProductSells" asp-action="Index">Show All Records</a>
</form>

<br />
<hr />

<table class="table table-bordered table-striped" id="productSells">
    <thead>
        <tr>
            <th>Product</th>
            <th>Store</th>
            <th>Price</th>
            <th>Date</th>
            <th>Operations</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Product</td>
                <td>@item.Store</td>
                <td>@item.Price</td>
                <td>@item.SoldDate.ToShortDateString()</td>
                <td>
                    <a href="/ProductSells/getchart/@item.ProductId/@item.StoreId" class="btn btn-primary">Show Price Chart on this Store</a>
                </td>
            </tr>
        }
    </tbody>
</table>

@section Scripts{
    <script src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#productSells').DataTable();
        });
    </script>
}
@section Styles{
    <link href="https://cdn.datatables.net/1.10.24/css/jquery.dataTables.min.css" rel="stylesheet" />
}

Task_One.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Task_One.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    @await RenderSectionAsync("Styles", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Task_One</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ProductSells" asp-action="Index">ProductSells</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Task_One.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>